#!/bin/sh
# /etc/networkd-dispatcher/routable.d/50-tzupdate

INTERFACE=$(echo "$json" | jq -r '.InterfaceName // empty')

# Only run on physical network interfaces
case "$INTERFACE" in
    eth*|en*|wlan*|wlp*)
        logger -t tzupdate-hook "Triggered on interface: $INTERFACE"
        /usr/bin/tzupdate
        ;;
    *)
        logger -t tzupdate-hook "Skipping interface: $INTERFACE"
        ;;
esac
